Add lz4/zstd codec support

diff --git a/shim/Dockerfile b/shim/Dockerfile
--- a/shim/Dockerfile
+++ b/shim/Dockerfile
@@ -48,6 +48,7 @@ ENV CMAKE_PREFIX_PATH="/opt/nvcomp:/opt/aws"
 
 WORKDIR /src
 COPY . .
+RUN grep -c "lz4" shim/CMakeLists.txt || echo "LZ4 NOT FOUND IN CMAKELISTS"
 
 ARG CMAKE_BUILD_TYPE=Release
 RUN cmake -S shim -B shim/build -G Ninja -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
